---
title: "Music_PredictionEDA"
author: "Pavani Samala"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
library(ezids)
loadPkg("tree")
```


Reading in the dataset: All come in as expected (date is a character, but we don't need this because it's not really realted to the song data)

```{r}
setwd("/Users/pavan/Desktop/Git/6101 project/DS-6101-Final")
music = data.frame(read.csv("music_genre.csv"))
str(music)
```

```{r}
# drop those blank genre values 
music = music[!(music$music_genre == ""),]

```



Prepossessing the Genre Column with dummy variables
```{r}
#genres as binary categorical data
new_genres<-c()
for (i in music$music_genre) 
  {if (i=="Electronic")
    new_genres<-append(new_genres,values='e')
  else
    new_genres<-append(new_genres,values='ne')}
music$new_genres<-new_genres

#

```

```{r}
music$new_genres = factor(music$new_genres)
music$music_genre = factor(music$music_genre)
music$mode = factor(music$mode)
music$key = factor(music$key)


str(music)
```


```{r}
# unbalanced data

library(caTools)
trainingRows <- sample(1:nrow(music), 0.7*nrow(music))
training <- music[trainingRows, ]
testing <- music[-trainingRows, ]
```



```{r}
library(partykit)
library(rpart)
loadPkg("rpart.plot")
loadPkg("rattle")
library(caret)
library(ISLR)

#binary genres
treefit1<-rpart(new_genres ~ popularity + acousticness + danceability + energy + key +liveness + loudness + mode + speechiness + valence, data=training,method="class", control = list(maxdepth = 14))
fancyRpartPlot(treefit1)

printcp(treefit1)
cm = confusionMatrix( predict(treefit1, type = "class"), reference = training$new_genres )

```



```{r}
#non-binary genres
treefit2<-rpart(music_genre ~ popularity + acousticness + danceability + energy + key +liveness + loudness + mode + speechiness + valence, data=training, method="class", control = list(maxdepth = 14))
fancyRpartPlot(treefit2)

printcp(treefit2)
cm = confusionMatrix( predict(treefit2, type = "class"), reference = training$music_genre)

```









```{r}
# balancing data
eee<-subset(music, new_genres == 'e')
nee<-subset(music, new_genres == "ne")
new<-rbind(eee, nee[1:5000,])

trainingRows <- sample(1:nrow(new), 0.7*nrow(new))
training_bal <- new[trainingRows, ]
testing_bal <- new[-trainingRows, ]
```

```{r}

treefit1_bal<-rpart(new_genres ~ popularity + acousticness + danceability + energy + key +liveness + loudness + mode + speechiness + valence, data=training_bal, method="class", control = list(maxdepth = 4))
fancyRpartPlot(treefit1_bal)
printcp(treefit1_bal)
cm = confusionMatrix(predict(treefit1_bal, type = "class"), reference = training_bal$new_genres)

```


```{r}

treefit2_bal<-rpart(music_genre ~ popularity + acousticness + danceability + energy + key +liveness + loudness + mode + speechiness + valence, data=training_bal, method="class", control = list(maxdepth = 4))
fancyRpartPlot(treefit2_bal)
printcp(treefit2_bal)
cm = confusionMatrix(predict(treefit2_bal, type = "class"), reference = training_bal$music_genre)

```


```{r, results = 'markup'}
loadPkg("class")

k10_new_genres=knn(train = training[,c("liveness", "energy")], test = testing[,c("liveness", "energy")], cl=training[,"new_genres"], k=10)
cm = confusionMatrix(k10, reference = testing[,"new_genres"] )
table(k10_new_genres)



k10_music_genre=knn(train = training[,c("liveness", "energy")], test = testing[,c("liveness", "energy")], cl=training[,"music_genre"], k=10)
cm = confusionMatrix(k10, reference = testing[,"new_genres"] )
table(k10_music_genre)

```



```